### ISSUE TITLE
Kahn's Algorithm table is rendered as <code><pre>

### ISSUE THREAD

**Issue by edbrannin** [gaultier/blog#11]
There's a good chance you've already noticed this, but just in case:

The table after `The full adjacency matrix for the employee graph in the example above looks like:` in https://gaultier.github.io/blog/kahns_algorithm.html is rendered as a code block, followed by an empty table:

<img width="854" alt="image" src="https://github.com/gaultier/blog/assets/121909/89087368-c226-4f2f-9fa6-47bb22377d00">

Maybe it would render correctly if the HTML weren't indented?

https://github.com/gaultier/blog/blame/master/kahns_algorithm.md#L184

(This is weird, because normally Markdown shouldn't process content directly inside HTML tags like the `<table>` unless it's surrounded by blank lines.  Maybe you have some sort of code-block preprocessor running before the Markdown parsing? Or maybe [pandoc](https://github.com/gaultier/blog/blob/master/Makefile#L14) is just misbehaving by default?)

**Comment by gaultier** [comment]
Thank you!
Apparently this was due to having multiple spaces between `<td>`, `<th>` and `<tr>` elements which made pandoc interpret the whole thing as a code block. Weird, but the fix is easy (`ef707ded4c87419d0c2c6aa286c57de97402b207`).

Thanks again!
