### ISSUE TITLE
SOCK_STREAM means TCP

### ISSUE THREAD

**Issue by erenon** [gaultier/blog#4]
Thanks for the nice article!

> SOCK_STREAM means TCP

I think this is incorrect, and misleading. Perhaps: "SOCK_STREAM means a sequenced, reliable, two-way, connection-based byte stream, as opposed to SOCK_DGRAM datagrams"

**Comment by gaultier** [comment]
Thanks, I'll quote the [wikipedia definition](https://en.wikipedia.org/wiki/Unix_domain_socket): 
> Valid socket types in the UNIX domain are:   SOCK_STREAM – for a stream-oriented socket
