### ISSUE TITLE
Wayland from scratch - wayland-logo.h file has different variable name

### ISSUE THREAD

**Issue by jimsbugs** [gaultier/blog#9]
Thanks for the well written and informative tutorial on how to use Wayland from scratch.  While experimenting with the program I ran into two problems, the first of which is that on my system (Debian 12 "bookworm"), the generated `wayland-logo.h` creates a variable named `wayland_ppm` rather than `wayland_logo` as referenced in the code.  The following fix allows the code to build and execute correctly on a Raspberry Pi 4 running the recently released Raspberry Pi OS 12 "bookworm":

```
--- wayland-logo.h.orig 2023-10-15 19:25:25.000814718 -0700
+++ wayland-logo.h      2023-10-15 19:26:37.120784764 -0700
@@ -1,4 +1,4 @@
-unsigned char wayland_ppm[] = {
+unsigned char wayland_logo[] = {
   0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
   0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
   0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
```

The patched code also builds on an x86_64 system running Debian 12, but fails with an unhandled event when run.  I'll submit a separate issue addressing that.

**Comment by gaultier** [comment]
Hello and thank you for your comment!
You are correct, xxd produces a variable named after the file name. It is something I should mention in the article and/or include the command to rename the variable to something more human friendly.

**Comment by gaultier** [comment]
I have added a note to explain this in the article : 2694e23f8a4f53589baab0bf9303d9b3b7c88c68
